version: "3"
services:
  website:
    image: nginx:latest 
    ports:
      - "8080:80" 
      - "443:443" 
    restart: always 
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      # - ./certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/:/etc/nginx/certs
      # - ./certbot/www:/etc/nginx/cert
      - ./public:/etc/nginx/html